export const salesReps = {
  prochazka: {
    id: 'prochazka',
    avatar: '/avatars/prochazka.jpg',
    name: 'Michal Procházka',
    phone: '+420 733 790 766',
    email: 'prochazka@imtos.cz',
    color: '#DC2626',
    region: 'Morava + východní Čechy',
    pscLabel: '517, 56x, 60x–66x, 68x, 69x, 75x–77x, 796–798',
  },
  dobrovolny: {
    id: 'dobrovolny',
    avatar: '/avatars/dobrovolny.jpg',
    name: 'Petr Dobrovolný',
    phone: '+420 770 132 088',
    email: 'dobrovolny@imtos.cz',
    color: '#EA580C',
    region: 'Vysočina + Pardubicko',
    pscLabel: '53x, 58x, 59x, 67x',
  },
  tosenovjan: {
    id: 'tosenovjan',
    avatar: '/avatars/tosenovjan.jpg',
    name: 'David Tošenovjan',
    phone: '+420 607 235 259',
    email: 'tosenovjan@imtos.cz',
    color: '#7C3AED',
    region: 'Severní Morava + Slezsko',
    pscLabel: '70x–74x, 78x, 790–795',
  },
  david: {
    id: 'david',
    avatar: '/avatars/david.jpg',
    name: 'Petr David jr.',
    phone: '+420 770 433 755',
    email: 'pdavid@imtos.cz',
    color: '#2563EB',
    region: 'Severní + střední Čechy',
    pscLabel: '1xx, 27x, 29x, 35x, 36x, 40x–47x, 50x, 51x, 54x, 55x',
  },
  kolar: {
    id: 'kolar',
    avatar: '/avatars/kolar.jpg',
    name: 'Petr Kolář',
    phone: '+420 723 436 790',
    email: 'kolar@imtos.cz',
    color: '#16A34A',
    region: 'Západní + jižní Čechy',
    pscLabel: '1xx, 25x, 26x, 28x, 30x–34x, 37x, 38x, 39x',
  },
  kaizer: {
    id: 'kaizer',
    avatar: '/avatars/kaizer.jpg',
    name: 'Jozef Kaizer',
    phone: '+421 911 981 238',
    email: 'kaizer@imtos.cz',
    color: '#D97706',
    region: 'Slovensko střed + východ',
    pscLabel: 'SK: stred + východ',
  },
  zilinka: {
    id: 'zilinka',
    avatar: '/avatars/zilinka.jpg',
    name: 'Roman Žilinka',
    phone: '+421 910 902 801',
    email: 'zilinka@imtos.cz',
    color: '#0891B2',
    region: 'Slovensko západ',
    pscLabel: 'SK: západ',
  },
};
