export const salesReps = {
  prochazka: {
    id: 'prochazka',
    avatar: '/avatars/prochazka.jpg',
    name: 'Michal Procházka',
    phone: '+420 733 790 766',
    email: 'prochazka@imtos.cz',
    color: '#DC2626',
    region: 'Morava',
    pscLabel: '517, 56x, 66x, 67x, 68x, 69x, 75x, 76x',
  },
  dobrovolny: {
    id: 'dobrovolny',
    avatar: '/avatars/dobrovolny.jpg',
    name: 'Petr Dobrovolný',
    phone: '+420 770 132 088',
    email: 'dobrovolny@imtos.cz',
    color: '#EA580C',
    region: 'Morava',
    pscLabel: '53x, 58x, 59x, 67x',
  },
  tosenovjan: {
    id: 'tosenovjan',
    avatar: '/avatars/tosenovjan.jpg',
    name: 'David Tošenovjan',
    phone: '+420 607 235 259',
    email: 'tosenovjan@imtos.cz',
    color: '#7C3AED',
    region: 'Morava',
    pscLabel: '73x, 74x, 78x, 79x',
  },
  david: {
    id: 'david',
    avatar: '/avatars/david.jpg',
    name: 'Petr David jr.',
    phone: '+420 770 433 755',
    email: 'pdavid@imtos.cz',
    color: '#2563EB',
    region: 'Čechy',
    pscLabel: '1x, 29x, 35x, 36x, 40x, 41x, 43x, 46x, 47x, 50x, 512, 54x, 55x',
  },
  kolar: {
    id: 'kolar',
    avatar: '/avatars/kolar.jpg',
    name: 'Petr Kolář',
    phone: '+420 723 436 790',
    email: 'kolar@imtos.cz',
    color: '#16A34A',
    region: 'Čechy',
    pscLabel: '1x, 25x, 26x, 28x, 33x, 34x, 37x, 38x, 39x',
  },
  kaizer: {
    id: 'kaizer',
    avatar: '/avatars/kaizer.jpg',
    name: 'Jozef Kaizer',
    phone: '+421 911 981 238',
    email: 'kaizer@imtos.cz',
    color: '#D97706',
    region: 'Slovensko střed + východ',
    pscLabel: 'SK: střed + východ',
  },
  zilinka: {
    id: 'zilinka',
    avatar: '/avatars/zilinka.jpg',
    name: 'Roman Žilinka',
    phone: '+421 910 902 801',
    email: 'zilinka@imtos.cz',
    color: '#0891B2',
    region: 'Slovensko západ',
    pscLabel: 'SK: západ',
  },
};

export const nutsMapping = {
  'CZ010': { reps: ['kolar', 'david'] },
  'CZ020': { reps: ['kolar', 'david'] },
  'CZ031': { reps: ['kolar'] },
  'CZ032': { reps: ['kolar'] },
  'CZ041': { reps: ['david'] },
  'CZ042': { reps: ['david'] },
  'CZ051': { reps: ['david'] },
  'CZ052': { reps: ['david', 'prochazka'] },
  'CZ053': { reps: ['dobrovolny', 'prochazka'] },
  'CZ063': { reps: ['dobrovolny'] },
  'CZ064': { reps: ['prochazka', 'dobrovolny'] },
  'CZ071': { reps: ['prochazka', 'tosenovjan'] },
  'CZ072': { reps: ['prochazka'] },
  'CZ080': { reps: ['tosenovjan'] },
  'SK010': { reps: ['zilinka'] },
  'SK021': { reps: ['zilinka'] },
  'SK022': { reps: ['zilinka'] },
  'SK023': { reps: ['zilinka'] },
  'SK031': { reps: ['kaizer'] },
  'SK032': { reps: ['kaizer'] },
  'SK041': { reps: ['kaizer'] },
  'SK042': { reps: ['kaizer'] },
};
